#!/usr/bin/env bash

script_dir=$(dirname $0)

hook_dir="$script_dir/pre-commit.d"

if [[ -d $hook_dir ]]; then
  stdin=$(cat /dev/stdin)

  for hook in $hook_dir/*; do
    filename="$(basename $hook)"
    echo "Running $filename hook"
    echo "$stdin" | $hook "$@"

    exit_code=$?

    if [ $exit_code != 0 ]; then
      exit $exit_code
    fi
  done
fi

exit 0
