set nocompatible                                      " be iMproved, required
filetype off                                          " required

" plugins
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'tpope/vim-fugitive'                           " Git wrapper
Plugin 'kien/ctrlp.vim'
Plugin 'mileszs/ack.vim'                              " search tool
Plugin 'scrooloose/nerdtree'
Plugin 'itchyny/lightline.vim'                        " status line
Plugin 'tpope/vim-surround'                           " quotes, brackets etc.
Plugin 'shougo/neocomplete.vim'                       " keyword completion
Plugin 'scrooloose/syntastic'                         " syntax checking
Plugin 'airblade/vim-gitgutter'
Plugin 'scrooloose/nerdcommenter'                     " comments
Plugin 'majutsushi/tagbar'                            " structure overview
Plugin 'terryma/vim-multiple-cursors'                 " faster selecting
Plugin 'mxw/vim-jsx'
Plugin 'tpope/vim-eunuch'                             " shell commands

call vundle#end()                                     " required
filetype plugin indent on                             " required

" general
set encoding=utf-8
set guifont=Monaco:h12                                " font & size
colorscheme monokai                                   " theme
set number                                            " line number
set cursorline                                        " current line
set autoread
set colorcolumn=100                                   " vertical line

" whitespace, indentation
set backspace=indent,eol,start
set autoindent
set tabstop=2 softtabstop=2 shiftwidth=2 expandtab smarttab shiftround
set list                                              " make whitespaces visible
set listchars=tab:│\ ,trail:•,extends:❯,precedes:❮
set linebreak
let &showbreak='↪ '
autocmd BufWritePre * :%s/\s\+$//e                    " remove trailing spaces on save

" mappings
nmap <C-Tab> :tabnext<CR>
nmap <C-S-Tab> :tabprevious<CR>

" nerdtree
map <C-n> :NERDTreeToggle<CR>
autocmd vimenter * NERDTree                           " open when starts up
set guioptions-=L                                     " disable scroll bar
let g:NERDTreeWinSize = 40                            " width

" Ack
if executable('ag')
  let g:ackprg = 'ag --vimgrep'
endif

" lightline
let g:lightline = {
  \ 'colorscheme': 'wombat',
  \ 'active': {
  \   'left': [ [ 'mode', 'paste' ],
  \             [ 'fugitive', 'filename', 'modified' ] ]
  \ },
  \ 'component_function': {
  \   'modified': 'LightLineModified',
  \   'fugitive': 'LightLineFugitive',
  \   'filename': 'LightLineFilename'
  \ }
  \ }

function! LightLineModified()
  if &filetype == "help"
    return ""
  elseif &modified
    return "+"
  elseif &modifiable
    return ""
  else
    return ""
  endif
endfunction

function! LightLineFugitive()
  return exists('*fugitive#head') ? fugitive#head() : ''
endfunction

function! LightLineFilename()
  return expand('%')
endfunction

" neocomplete
let g:neocomplete#enable_at_startup = 1               " open when starts up

" syntastic
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_ruby_checkers = ['rubocop', 'mri']

" nerdcommenter
let NERDSpaceDelims = 1                               " add 1 space after comment symbol

" tagbar
nmap <F8> :TagbarToggle<CR>

" multiple cursors
let g:multi_cursor_next_key = '<C-d>'

" jsx
let g:jsx_ext_required = 0
