#!/usr/bin/env ruby

require 'English'

hits = []

checks = {
  '\.rb$' => ['binding\.pry', 'debugger', 'dupa'],
  '\.haml' => ['binding\.pry', 'dupa'],
  '\.js' => ['debugger']
}

# Find the names of all the filenames that have been (A)dded (C)opied or (M)odified
filenames = `git diff --cached --name-only --diff-filter=ACM`.split("\n")

filenames.each do |filename|
  # Perform special checks for _spec filenames (rspec tests)
  checks.each do |filename_pattern, patterns|
    next unless filename.match?(filename_pattern)

    patterns.each do |contents_pattern|
      results = `git diff --cached  #{filename} | grep "^\+[^+]" | grep "#{contents_pattern}"`
                .split("\n")
                .map { |result| result.sub(/^\+[\s\t]*/, '') }

      next if $CHILD_STATUS != 0

      # Add the relevant change with line number to the hits array
      results.each do |keyword|
        hits << "#{filename}:" + `grep -n '#{keyword}' #{filename}`.sub(/:\s+/, ' ').chomp
      end
    end
  end
end

exit 0 if hits.empty?

puts "\e[33m>>> Please remove forbidden words from these files before committing\e[0m"
puts hits.join("\n")
exit 1
