# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="unijewski"
DISABLE_UNTRACKED_FILES_DIRTY="true"

plugins=(git bundler macos rails ruby docker-compose)

export PATH="$PATH:$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$HOME/.rvm/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin"

source $ZSH/oh-my-zsh.sh

export BUNDLER_EDITOR="code --wait"
export EDITOR="code --wait"
export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && . "/usr/local/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion
export TERM=xterm-256color
export VIMRC="~/.vimrc"

alias dm=docker-machine

gfr() {
  git reset --soft HEAD~1 && git restore --staged .
}
