# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="unijewski"
DISABLE_UNTRACKED_FILES_DIRTY="true"

plugins=(git bundler macos rails ruby docker-compose)

source $ZSH/oh-my-zsh.sh

export PATH="$HOME/bin:/opt/homebrew/bin:/opt/homebrew/sbin:$HOME/.rvm/bin:$PATH"

export BUNDLER_EDITOR="code --wait"
export EDITOR="code --wait"
export TERM=xterm-256color
export VIMRC="~/.vimrc"
export LANG="en_GB.UTF-8"
export HISTSIZE=500000
export SAVEHIST=100000

# export NVM_DIR="$HOME/.nvm"
# [ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm
# [ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

alias dm=docker-machine

gfr() {
  git reset --soft HEAD~1 && git restore --staged .
}

source $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh
