export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="unijewski"
DISABLE_UNTRACKED_FILES_DIRTY="true"
plugins=(git bundler macos rails ruby docker-compose)
source $ZSH/oh-my-zsh.sh
[[ "$TERM_PROGRAM" == "vscode" ]] && . "$(code --locate-shell-integration-path zsh)"

export PATH="$HOME/bin:/opt/homebrew/bin:/opt/homebrew/sbin:$HOME/.rvm/bin:$PATH"

export BUNDLER_EDITOR="code --wait"
export EDITOR="code --wait"
export HISTSIZE=500000
export LANG="en_GB.UTF-8"
export SAVEHIST=100000
export TERM=xterm-256color
export VIMRC="~/.vimrc"

alias dm=docker-machine

export NVM_DIR="$HOME/.nvm"
[ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init - zsh)"

gfr() {
  git reset --soft HEAD~1 && git restore --staged .
}

source $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh

gitpullall() {
  for dir in */; do
    cd "$dir"
    if [ -d .git ]; then
      current_branch=$(git branch --show-current)
      if [ "$current_branch" != "main" ]; then
        git checkout main
      fi
      echo "🔄 Updating repository in $dir"
      git pull origin main
    else
      echo "⏭️  $dir is not a Git repository - skipping"
    fi
    cd ..
  done
}
